<a href="https://colab.research.google.com/github/PhinyadaPhen/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ matrix)

#Numpy Array

สร้าง numpy array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) # สร้าง numpy array ที่มี 2 แถว 3 หลัก 

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

## matrix transpose

In [6]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## สร้าง matrix เริ่มต้น (Zeros,ones)

In [7]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix randoom

In [12]:
np.random.randn(5,5) # randoom เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[ 0.7204939 , -1.27270942, -1.44124554,  0.36392829, -0.39530003],
       [-1.33525749,  0.52745897,  0.56487222,  0.51294733, -0.25475116],
       [-0.35744265, -0.29516064,  0.48282765,  1.31707583, -0.26728242],
       [ 1.88030106, -1.64646339,  0.24284762,  0.95786966,  0.74643735],
       [ 2.39857932,  1.3242352 , -0.55776196, -0.89792143, -0.22399988]])

In [13]:
2 + (5*np.random.randn(3,3)) # randoom เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[ 8.72406309,  0.74675735,  2.40336071],
       [ 5.72844169,  2.38605374,  2.12395747],
       [-6.47099844,  0.42440734,  2.38486109]])

In [16]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็ม ระหว่าง [5,11) ขนาด (4,5)

array([[ 7,  6,  9, 10,  9],
       [ 8,  6,  5,  6,  8],
       [ 5,  9,  9,  8,  7],
       [ 8,  5, 10,  7,  6]])